# Cloudflare Pages Configuration
name = "protekanalitik-com"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# Environment variables should be set in Cloudflare Pages Dashboard
# Settings -> Environment variables:
# GMAIL_USER = "websiteform@protekanalitik.com"
# GMAIL_APP_PASSWORD = "your-app-password"
# NODE_ENV = "production"
