# This is the valid configuration file for Cloudflare Pages.
# It specifies the output directory for the Next.js build, resolving the 404 error.
pages_build_output_dir = ".next"
compatibility_date = "2024-07-01"
