# Cloudflare Pages Configuration
# This file ensures that Cloudflare Pages uses the correct build settings.

name = "protek-analitik-website"
compatibility_date = "2024-07-01"

# The output directory for the Next.js build.
pages_build_output_dir = ".next"
